### ISSUE TITLE
Implement Tools / Actions in the component

### ISSUE THREAD

**Issue by nickscamara** [mendableai/mendable-nextjs-chatbot#4]
Mendable.ai just launched a feature called tools and actions that allows the AI to use tools to complete a task. (An action is essentially the same as a tool but we differentiate it in the UI)

Simple Objective: **The goal here would be to implement the loading states for when the AI is loading tools, is using a tool or had a tool error just like we have in our components.**

All we need to is to capture the below stream events and present that nicely to the users when the AI is loading/using a tool:

Feel free to use this Mendable anon_key for testing `25f4cba6-f997-4991-bf4f-dbb5fab8f7bd`

and here is query you can use to test tools `What's the weather in SF right now?` - it will cache the responses if you test too fast, so modify the query accordingly.

**Here is the API for the streaming of tools:**

Chunk <|loading_tools|> only shows if "Tools and Actions" is enabled. That chunk will contain "true" if AI is looking for tools to take action on the user's request.

Chunk <|tool_called|> only shows if "Tools and Actions" is enabled. That chunk will contain an object with the name of the tool that was called and a `is_action` boolean. {name: tool_name , is_action: true/false}.

Chunk <|tool_error|> only shows if "Tools and Actions" is enabled. That chunk will contain a string with the error message.

Reference can be found here: 
https://docs.mendable.ai/mendable-api/chat#stream-response
https://docs.mendable.ai/tools#using-via-api

Here is a reference UI component that we use for our other components. Feel free to use it/adapt it to make the UI similar

```
import React from "react";
import { AiOutlineTool, AiOutlineWarning } from "react-icons/ai";
import { CgSpinner } from "react-icons/cg";
import { MendableTool } from "../../types";
import { BsLightningCharge } from "react-icons/bs";

export default function UsingTool({
  loading,
  error,
  currentTool,
  className,
}: {
  loading: boolean;
  error?: string;
  currentTool: MendableTool;
  className?: string;
}) {
  return (
    <div
      onClick={() => {
        if (error) {
          alert(error);
        }
      }}
      title={error ?? "Using " + currentTool.name + " Tool"}
      className={
        `${className} ms-flex ms-w-fit ms-items-center ms-rounded-md ms-border ms-px-2 ms-py-[5px] ms-text-xs hover:ms-cursor-pointer` +
        (error
          ? " ms-border-orange-500 ms-bg-orange-500/25 ms-text-orange-500"
          : currentTool.is_action
          ? " ms-border-yellow-400 ms-bg-yellow-400/25 ms-text-yellow-400"
          : " ms-border-primary ms-bg-primary/25 ms-text-primary")
      }
    >
      {loading ? (
        <CgSpinner className="ms-mr-1 ms-animate-spin" size={20} />
      ) : error ? (
        <AiOutlineWarning className="ms-mr-1" size={20} />
      ) : currentTool.is_action ? (
        <BsLightningCharge
          className="ms-mr-1 ms-fill-yellow-400"
          size={18}
        />
      ) : (
        <AiOutlineTool className="ms-mr-1" size={20} />
      )}
      {currentTool.name} {!currentTool.is_action ? "Tool" : ""}
    </div>
  );
}
```

**Comment by Gmin2** [comment]
/attempt #4
can i get assigned

<div id="algora" />

| [Algora profile](https://console.algora.io/@/Min2who) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Min2who | 6 bounties from 4 projects | <div align="center">HTML, JavaScript</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clrgqpb820006jn0fd2230phi/cancel-attempt) |

**Comment by nickscamara** [comment]
@Min2who yes!

**Comment by uday-biswas** [comment]
its been 19 hours since @Min2who was assigned , can i be assigned now
/attempt #4

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clrgqpb820006jn0fd2230phi/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by nickscamara** [comment]
@uday-biswas Let me check with @Min2who first. 

@Min2who have you made any progress? Let me know, otherwise I will assign to @uday-biswas.

**Comment by Gmin2** [comment]
@nickscamara 

> @uday-biswas Let me check with @Min2who first.
> 
> @Min2who have you made any progress? Let me know, otherwise I will assign to @uday-biswas.

@nickscamara give me a day i will submit a pr

**Comment by uday-biswas** [comment]
@nickscamara  can i work parallelly , if solved i will submit a pr

**Comment by nickscamara** [comment]
Hey @uday-biswas I would recommend waiting at least 24 hours. In the meantime, feel free to check other bounties or explore starting new template apps with Mendable.

**Comment by Gmin2** [comment]
@nickscamara 
as mendable_stream.ts only returns chunk how do i  return the metadata 
Can i return `parsedData`  from `parseMendableStream()` and filter it in the `bubble.tsx` is that solution look good
?

**Comment by nickscamara** [comment]
@Min2who Yea that's fine!

**Comment by Gmin2** [comment]
> @Min2who Yea that's fine!

@nickscamara where do i render the loading state can you specify where exactly do you need and it should render when the chat is loading/using a tool/error right?
![image](https://github.com/mendableai/mendable-nextjs-chatbot/assets/127925465/e0003244-c34a-4758-ab1e-9b3edb96b0f1)

**Comment by nickscamara** [comment]
Between AI label and the text works!

**Comment by Gmin2** [comment]
@rishi-raj-jain wanna take this?

**Comment by rishi-raj-jain** [comment]
@Min2who 

Hey, nope I'm proposing a new issue for me to work on :D

**Comment by Gmin2** [comment]
@uday-biswas go ahead with this one!

**Comment by nickscamara** [comment]
@Min2who was there any blocker you faced? It looked like you were at the finish line.

**Comment by Gmin2** [comment]
@nickscamara may i submit the pr regarding the work i have done

**Comment by nickscamara** [comment]
@Min2who yes, go for it! I will take a look

**Comment by nickscamara** [comment]
@Min2who any updates?

**Comment by Gmin2** [comment]
> @Min2who any updates?

@nickscamara not too much progress
i am giving up on it,I think in order to implement this we need to change a lot of code (especially the ai library of nextjs)

**Comment by nickscamara** [comment]
@Min2who Sounds good, nw. @uday-biswas wanna attempt it?

**Comment by rishi-raj-jain** [comment]
@nickscamara 

Once https://github.com/mendableai/mendable-nextjs-chatbot/pull/7 is merged, may you assign me this as well? I'd love to crush it.

**Comment by nickscamara** [comment]
@rishi-raj-jain assigning you right now!

**Comment by rishi-raj-jain** [comment]
@nickscamara @ericciarla 

Can we update this bounty to be at least $40? You saw in #7 I give my best.

**Comment by rishi-raj-jain** [comment]
(Just asking)

**Comment by nickscamara** [comment]
@rishi-raj-jain bumped to $30. That's the budget we have for it now. And thanks for doing a great job at #7

**Comment by rishi-raj-jain** [comment]
Cool, thanks! On it!
