### ISSUE TITLE
Mendable Astro Chatbot

### ISSUE THREAD

**Issue by rishi-raj-jain** [mendableai/mendable-nextjs-chatbot#5]
@nickscamara

Per your comment on other issue https://github.com/mendableai/mendable-nextjs-chatbot/issues/4#issuecomment-1895966976

> explore starting new template apps with Mendable

I'd love to make one for Astro: `mendable-astro-chatbot`. Can you create the repo, assign this issue to me and put a bounty on it?

**Comment by nickscamara** [comment]
Hey @rishi-raj-jain, sorry for taking so long to respond to this issue. Thanks for the enthusiasm! I chatted with the team and we think that Astro is not a priority right now, but as you can see we are opening a lot more bounties. If we decide that this should be built, we will reopen it and tag you on it. Thanks!

**Comment by rishi-raj-jain** [comment]
@nickscamara Super! I'm always excited about Astro!
