### ISSUE TITLE
Implement share conversation button to chat component

### ISSUE THREAD

**Issue by ericciarla** [mendableai/mendable-nextjs-chatbot#6]
We want to add a share conversation button that copies a link to the conversation to your clipboard and so people can easily share convos. Ideally when the button is clicked a little message says, "Conversation link copied to dashboard".

To implement this, all you need to do is hash the conversation data and pass it as a query parameter. Then find a way to decode the hash and display the conversation if a query parameter exists.

**Comment by rishi-raj-jain** [comment]
Can I be assigned this?

**Comment by ibishal** [comment]
/attempt #6
can i get assigned 

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clrqil8ri000gjk0fo7w7qvw7/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by mogery** [comment]
> To implement this, all you need to do is hash the conversation data and pass it as a query parameter. Then find a way to decode the hash and display the conversation if a query parameter exists.

I've done stuff like this before, and unfortunately you start hitting URL length limits really fast with this method.

**Comment by rishi-raj-jain** [comment]
@ericciarla 

Thanks for assigning!

> Unfortunately you start hitting URL length limits really fast with this method.

What are your thoughts on this?

**Comment by ericciarla** [comment]
Going to assign this to @rishi-raj-jain first.

Thanks for the request @ibishal and advice @mogery.

The conversations should not be longer than 6 total messages (AI and human combined) so we don't think this should be a problem.

**Comment by rishi-raj-jain** [comment]
Awesome, glad to have it all figured!

**Comment by ericciarla** [comment]
@rishi-raj-jain Awesome! Just wondering, what is your estimated delivery time?

**Comment by rishi-raj-jain** [comment]
@ericciarla Hour at maximum.
